# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "4096"
  end
config.vm.define "web1" do |web|
  web.vm.box = "ubuntu/focal64"
  web.vm.hostname = "webserver1.test"
  web.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  web.vm.network :private_network, ip: "192.168.56.22"
  web.vm.synced_folder ".", "/vagrant"
  web.vm.provision "shell", inline: <<-SHELL
  apt-get update
  apt-get install -y apache2 php libapache2-mod-php php-mysql
  rm /var/www/html/index.html
  mv /vagrant/index.php /var/www/html/index.php
  mv /vagrant/web-db.php /var/www/html/web-db.php
  SHELL
end
config.vm.define "web2" do |web|
    web.vm.box = "ubuntu/focal64"
    web.vm.hostname = "webserver2.test"
    web.vm.network :private_network, ip: "192.168.56.23"
  #  web.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  #  web.vm.synced_folder ".", "/vagrant"
    web.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y apache2
      SHELL
end

config.vm.define "db" do |db|
  db.vm.box = "ubuntu/focal64"
  db.vm.hostname = "database.test"
  db.vm.network :private_network, ip: "192.168.56.24"
  #config.vm.network "forwarded_port", guest: 3306, host: 3306
  db.vm.synced_folder ".", "/vagrant"
 # db.vm.provision "shell", inline: <<-SHELL
  #sudo apt update -y
  #sudo apt install apache2 -y
  #apt-get update
  #apt-get install -y apache2
  #apt-get install mysql-server -y
  #sudo apt install mysql-server -y
  #SHELL
  config.vm.provision :shell, path: "bootstrap.sh"
end

end

